### PR TITLE
Create Measure interia in Part.py

### PR DESCRIPTION
**Pull request by ptm-tm**
add measure interia in part

### CODE REVIEW

**Comment by ptm-tm** [comment]
im close prev pull and open new

**Comment by evereux** [comment]
To keep the naming conventions of examples consistent with the rest of the project please rename file to `example__inertia__001.py`. 
___
Please change the docstring to the following to make for easier reading comprehension
```
    Example - Inertia - 001:
	
    Catia must be running with a Part open that contains a solid object within the MainBody (PartBody).

    This example will only measure the inertia for the MainBody. Additional PartBodies will be ignored.
	
    Options for measure main body is not use:
    If you Granularity_mode sets to 1 for all bodies
    and interia=spa_i.add(body) change to interia=spa_i.add(part) then
    in this case you can granularity_mode sets to 1 for all bodies
    or granularity_mode sets to 0 for main body
```

I don't fully understand the granularity_mode explanaition. I'll have a read up on that ...
___


* imports should be ordered as shown below:

```python
##########################################################
# insert syspath to project folder so examples can be run.
# for development purposes.
import os
import sys

sys.path.insert(0, os.path.abspath("..\\pycatia"))
##########################################################


from pycatia import catia
from pycatia.mec_mod_interfaces.part import Part


```

You put the imports for pycatia before adding the system path so your example won't work for me.

___

How about initialising the inertia object so we can quickly navigate to the inertia class method within our IDE.

```python
interia = Inertia(spa_i.add(body).com_object)
```
___

Instead of calling the print function for each element of a tuple how about doing this:
```python
print(f'center of gravity\n'
      f'X={GOC[0]}\n'
      f'Y={GOC[1]}\n'
      f'Z={GOC[2]}')
```

It looks cleaner and only calls the print function once as opposed to four times in this case.

**Comment by ptm-tm** [comment]
ok i will fix
but pylint? show me error
изображение

**Comment by evereux** [comment]
> but pylint? show me error

The structure of the project is thus:
```
\pycatia (project root)
    \examples
        example__intertia__001.py
    \pycatia (the application)
```

Due to the location of `example__intertia__001.py` python doesn't know where pycatia is so running your original script throws an error along the lines of `cannot import module pycatia`.

This is why every example has the folllowing:

```python
##########################################################
# insert syspath to project folder so examples can be run.
# for development purposes.
import os
import sys

sys.path.insert(0, os.path.abspath("..\\pycatia"))
##########################################################
```

Please read the text above. 

This inserts the relative pycatia path so python can then import from pycatia. This is only required due to the examples being in the `/examples` folder. If the examples where in the project root we wouldn't have to do this.

Now, if it works for you I've got to wonder why? Do you have pycatia installed in your github cloned repository environment (check results of `pip freeze`? If you have, you should remove it. It might explain some of the weird things you've reported elsewhere.

**Comment by ptm-tm** [comment]
im change input, its not important for me. i have diff installed pycatia and github cloned))) i dont know how make it in one place

**Comment by evereux** [comment]
> i dont know how make it in one place

You shouldn't.


```
\pycatia (github clone)
   \...
    \examples
    \env *1
    \pycatia
    \...    
```


```
\pycatia (uses pypi pycatia)
    \...
    \env *2
    \...    
````

Notice how each has it's own virtual environment?

\*1 has the requirements installed from requirements.txt
\*2 has pycatia installed from pypi.

I suspect you aren't using virtual environments but just one global one?

**Comment by ptm-tm** [comment]
hmm you has some tutorials.? bcause i have another structure..
like this
изображение

**Comment by ptm-tm** [comment]
your 

> To keep the naming conventions of examples consistent with the rest of the project please rename file to `example__inertia__001.py`.
> 
> Please change the docstring to the following to make for easier reading comprehension
> 
> ```
>     Example - Inertia - 001:
> 	
>     Catia must be running with a Part open that contains a solid object within the MainBody (PartBody).
> 
>     This example will only measure the inertia for the MainBody. Additional PartBodies will be ignored.
> 	
>     Options for measure main body is not use:
>     If you Granularity_mode sets to 1 for all bodies
>     and interia=spa_i.add(body) change to interia=spa_i.add(part) then
>     in this case you can granularity_mode sets to 1 for all bodies
>     or granularity_mode sets to 0 for main body
> ```
> 
> I don't fully understand the granularity_mode explanaition. I'll have a read up on that ...
> 
>     * imports should be ordered as shown below:
> 
> 
> ```python
> ##########################################################
> # insert syspath to project folder so examples can be run.
> # for development purposes.
> import os
> import sys
> 
> sys.path.insert(0, os.path.abspath("..\\pycatia"))
> ##########################################################
> 
> 
> from pycatia import catia
> from pycatia.mec_mod_interfaces.part import Part
> ```
> 
> You put the imports for pycatia before adding the system path so your example won't work for me.
> 
> How about initialising the inertia object so we can quickly navigate to the inertia class method within our IDE.
> 
> ```python
> interia = Inertia(spa_i.add(body).com_object)
> ```
> 
> Instead of calling the print function for each element of a tuple how about doing this:
> 
> ```python
> print(f'center of gravity\n'
>       f'X={GOC[0]}\n'
>       f'Y={GOC[1]}\n'
>       f'Z={GOC[2]}')
> ```
> 
> It looks cleaner and only calls the print function once as opposed to four times in this case.

I hope I fixed everything :) pls check

**Comment by evereux** [comment]
> hmm you has some tutorials.? bcause i have another structure.. like this изображение

I don't think you need any tutorials. I've given you descriptions above on how it should be laid out.

Your problem here is having one folder with one virtual environment and having two instances of pycatia (github and pypi). You need to seperate the projects with seperate venvs as I described above. I don't know how to make it clearer sorry.

**Pull request merged**
