### PR TITLE
Provide Product.type property

### PR DESCRIPTION
**Pull request by Tian-Jionglu**
`Product.is_catpart` and `Product.is_catproduct` are wonderful methods. But it fails to distinguish *component* from *catproduct*.
`Product.type` make this function possible.

### CODE REVIEW

**Comment by Tian-Jionglu** [comment]
Here is an example .

```
from pycatia import catia
caa = catia()
documents = caa.documents
document = documents.add("Product")
product = document.product()
product.part_number = "Car"
products = product.products

# create the children
products.add_new_product("Body")
products.add_new_component("Product", "Engine")
products.add_new_component("Part", "Wheel")

# pirnt the information of children
for sub_prd in products:
    print(f"{sub_prd.name} is {sub_prd.type}")
```

**Comment by evereux** [comment]
I like it, a lot!

A couple of comments:

Please add 
```python
    :return: str
    :rtype: str
```

Please change:
```
Return the type of product, catporduct, catpart or component
```
to
```
Returns the type of product (catproduct, catpart or component).
```

I would personally prefer to not lowercase CATPart or CATProduct and if there isn't a good reason to can we then change the docstring above to read `Returns the type of product (CATProduct, CATPart or Component)` and also return `Component` as opposed to `component`.

**Comment by Tian-Jionglu** [comment]
Updated via commit https://github.com/evereux/pycatia/pull/65/commits/a0b9275d142214b7a2d12b1bdea6a0881663f515.
Honestly, lowercasing is just copied from `Product.is_product`. It is changed to "CATProduct", "CATPart", "Component" now.

**Comment by evereux** [comment]
> Updated via commit [a0b9275](https://github.com/evereux/pycatia/commit/a0b9275d142214b7a2d12b1bdea6a0881663f515).
> Honestly, lowercasing is just copied from `Product.is_product`. It is changed to "CATProduct", "CATPart", "Component" now.

I did that there in case the user had for some reason changed the file extension.

**Comment by Tian-Jionglu** [comment]
> I did that there in case the user had for some reason changed the file extension.

(If what I understand is right...)
This remind me that this year I ever got data like "test.catpart" and "test.catpart.CATPart" from Teamcenter (PLM software). Even Teamcenter was cheated because of  some bug. We got no answer about this problem. Since the probability of this problem is quite low, we just let it go and fixed the wrong data. 😅 
I've just test to save a "test.CATPart" as "test.catpart", and got "test.CATPart" as a result. So I think the code we provide would be safe in most cases.

**Pull request merged**
