### PR TITLE
Add input box

### PR DESCRIPTION
**Pull request by ptm-tm**
Added standart input box promt in catia

### CODE REVIEW

**Comment by evereux** [comment]
Thanks for this.

I have a few comments:
* `promt` is mis-spelt and should be `prompt`.
* please use reST style docstrings so it's consistent with the rest of this project.
* there is nothing that tells me what is returned (it's a string).
* the inputs `title` and `default` are missing type hints. (see below)
* the method output is missing a type hint. (see below)
```python
def input_box(
        self, 
        prompt: str,
        title: str = '':, 
        default: str = '') -> str:
```
* `If you omit title,the application name is placed in the title bar` - this statement isn't true, it was just empty so I think this statement can be removed.

**Comment by ptm-tm** [comment]
thx for change branch ( im clone dev but why push to master idk). im  not add xpos,ypos , helpfile and context to input box but its not nessesary.
some method im dont know) im newbe

**Comment by ptm-tm** [comment]
https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/inputbox-function

im clone this func

**Comment by evereux** [comment]
> im not add xpos,ypos , helpfile and context to input box but its not nessesary.

Agreed.

>  im newbe

No worries. 👍 You've made some helpful contributions.

I did read the contents of that link referenced in the doc string. It was helpful when trying it out.

**Comment by ptm-tm** [comment]
ok im try to fix it later (2-4days). some mistake- bcause eng is not me natural lang)))).
and i cant correctly fix it in dev mode
some problem- i have 2 diff win ( win7 and 10)
github desctom dont work in win 7 and git cant auth in win7
i have 2 diff ide ( spyder and vscode)))
and i need 2 copy application.py from git dir to install path dir when i debug it...

**Comment by evereux** [comment]
I've swapped the branch back to `master`. When you're done I can change it back to developement then merge.

**Comment by evereux** [comment]
ps: I use gitkraken myself. It has quite a nice interface.

**Comment by evereux** [comment]
> and i need 2 copy application.py from git dir to install path dir when i debug it...

hmm, not sure why you would have to do that? something isn't set-up right?

**Comment by ptm-tm** [comment]
> > and i need 2 copy application.py from git dir to install path dir when i debug it...
> 
> hmm, not sure why you would have to do that? something isn't set-up right?

maybe i dont find setup help) but when i git clone- i have 2 version pycatia ( installed in venv and cloned by git).
spyder worked with git version but run installed) vs code worked and start installed version... ( manually its work )
 im use python 2-3 times to write scripts. i cant find how install dev version and update it and dont see always "your fork is need update... " and some other thing like kwarg with name and without default values like in this function

**Comment by ptm-tm** [comment]
>     * `If you omit title,the application name is placed in the title bar` - this statement isn't true, it was just empty so I think this statement can be removed.
i fix errors.
title can be changed. i think some time its helpfull
изображение

**Comment by evereux** [comment]
I made a bit of a cock up here. Forgot to merge into the developement branch so had to revert from the master branch. Then couldn't figure out how to re-open this pull request. 😖 

Anyways, I've made this change manually to the developement branch. Please see the changes I've made regarding the doc strings. This is what I meant when I said above: 

> please use reST style docstrings so it's consistent with the rest of this project.

___

With regards to:

> title can be changed. i think some time its helpfull

I wasn't suggesting otherwise. 

> `If you omit title, the application name is placed in the title bar` - this statement isn't true, it was just empty so I think this statement can be removed.

The application name is not placed in the title bar if it's omitted so the statement is false. I've removed that statement.

**Comment by ptm-tm** [comment]
im try... but if i cant see result- i cant write it correctly.

**Comment by ptm-tm** [comment]
> I'm not sure I understand?

i cant debug rst for example/

**Pull request merged**
