### PR TITLE
Update viewer_3d.py

### PR DESCRIPTION
**Pull request by philippjaeger**
bug fixed in line 407: "Rotate" changed to "rotate"

### CODE REVIEW

**Comment by evereux** [comment]
Can you provide some code that shows that your change fixed an issue please?

This change doesn't make a lot of sense to me. `self.viewer_3d.Rotate(i_axis, i_angle)` > `viewer_3d` is the COM object and `Rotate` is the method on that COM object which should be a capital letter.

**Comment by philippjaeger** [comment]
I am using Python 3.12.4 and CATIA V5-6 R2021. 

With the capital "R", the following error message is displayed in the command window:

  File "F:\Python\pycatia_scripts\erstellung_blade.py", line 82, in <module>
    pycatia.in_interfaces.viewer_3d.Viewer3D(viewer_3D).rotate(xy_Ebene, -114.2)
  File "F:\Python\pycatia_scripts\env\Lib\site-packages\pycatia\in_interfaces\viewer_3d.py", line 407, in rotate
    return self.viewer_3d.Rotate(i_axis, i_angle)
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Viewer3D' object has no attribute 'Rotate'. Did you mean: 'rotate'?

("erstellung_blade.py" is my user-script) 

If i change it to the lower case "r" as proposed in the pull request, the error disappears and everything works as expected. 
This error was also noticed by one of my colleagues (same software), so it is not a individual case.

I should note, that my experience with python is very limited, but it seemed to be the standard way to let you know about the issue and a possible fix.

best regards
philipp

**Comment by evereux** [comment]
Thanks for the reply. Very interesting. 

I'll look into this more.

**Comment by evereux** [comment]
I've written this small test script which requires an open CATPart. 

```python

from pycatia import catia
from pycatia.mec_mod_interfaces.part_document import PartDocument

caa = catia()
part_document: PartDocument = caa.active_document
part = part_document.part
axis_systems = part.axis_systems
abs_axis = axis_systems[0]
abs_y_axis = abs_axis.get_y_axis()

windows = caa.windows
window = windows[0]
viewers = window.viewers
viewer = viewers[0]
viewer_3d = viewer.create_viewer_3d()
viewer_3d.rotate(abs_y_axis, 110)

viewer.update()
```

This works as expected with no changes to pycatia. If I change `Viewer3D.rotate()` internals to the lowercase `return self.viewer_3d.rotate(i_axis, i_angle)` it still works. Had a feeling it might be case insensitive.

Can you try and run my script above please with an unpatched version of pycatia that calls `return self.viewer_3d.Rotate(i_axis, i_angle)`?

@Djey51 @deloarts @Mithro86 
Could you test this script on the latest versions of CATIA V5 you have access to if you can please?

**Comment by deloarts** [comment]
works in V5 R33

**Comment by Mithro86** [comment]
...and works for R30.

**Comment by philippjaeger** [comment]
I put the test script in a file called „testscript.py“:

------------------------------------------------
from pycatia import catia
from pycatia.mec_mod_interfaces.part_document import PartDocument

caa = catia()
part_document: PartDocument = caa.active_document
part = part_document.part
axis_systems = part.axis_systems
abs_axis = axis_systems[0]
abs_y_axis = abs_axis.get_y_axis()

windows = caa.windows
window = windows[0]
viewers = window.viewers
viewer = viewers[0]
viewer_3d = viewer.create_viewer_3d()
viewer_3d.rotate(abs_y_axis, 110)

viewer.update()
---------------------------------------


I tried using it in pycatia.
It threw the following error:

----------------------------------------
(env) F:\Python\pycatia_scripts>python testscript.py
Traceback (most recent call last):
  File "F:\Python\pycatia_scripts\testscript.py", line 8, in <module>
    abs_axis = axis_systems[0]
               ~~~~~~~~~~~~^^^
  File "F:\Python\pycatia_scripts\env\Lib\site-packages\pycatia\mec_mod_interfaces\axis_systems.py", line 106, in __getitem__
    raise StopIteration
StopIteration

(env) F:\Python\pycatia_scripts>part
Der Befehl "part" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
---------------------------------------------------

Last two lines roughly translate to „ the command „part“ is either spelled wrong or could not be found“.

I would guess, that i have some other underlying problems or it is simply a user error, if it worked fort he other testers. 
Since the code doesnt get to the viewer-part, it also doesnt matter which pycatia version i use (patched or unpatched).

**Comment by evereux** [comment]
@deloarts @Mithro86 Thankyou! ❤️ 

@philippjaeger That error message means pycatia couldn't get the first `AxisSystem` in the `AxisSystems` collection. If it fails getting the first one it probably then means there aren't any AxisSystems. Can you manually add an AxisSystem to the CATPart you're testing this on? Within CATIA V5 `Insert` > `AxisSystem` then try re-running it. I forgot to mention your CATPart should have an axis system.

**Comment by philippjaeger** [comment]
I didnt think of that...
now it works without errors with both versions, patched or unpatched.

**Pull request closed without merging**
