### PR TITLE
Added new interface: knowledge

### PR DESCRIPTION
**Pull request by Luanee**
...to add, change and remove parameter(s), parameter set(s), relations and formulas

### CODE REVIEW

**Comment by Luanee** [comment]
I'm glad you like this interface :)

**Comment by evereux** [comment]
Yeah, good work on this, thanks! It's great to get other contributions. :)

Writing the tests I think I've found a problem with Parameter inheritance. For example if I create a new boolean parameter I can't directly access it's name method.

This fails when I expect it work:

    with CATIADocHandler(cat_part_blank) as handler:
        document = handler.document
        part = document.part()
        parameters = Parameters(part.part.Parameters)

        new_boolean_parm = parameters.create_boolean('new_boolean', True)
        assert new_boolean_parm.name == r'CF_Part_Blank\new_boolean'

This is OK:

    with CATIADocHandler(cat_part_blank) as handler:
        document = handler.document
        part = document.part()
        parameters = Parameters(part.part.Parameters)

        assert new_boolean_parm.parameter.name == r'CF_Part_Blank\new_boolean'


I might be missing something but I'll look into this more tomorrow.

**Comment by Luanee** [comment]
I have to thank you. Because of your python library I was able to build up my master thesis successfully last year :) And it simply combines two very interesting areas: programming and CAD design!

I think this has to do with how I built the specific parameter classes. I define the parameter in each of these classes as follows:

```
class BoolParam(Parameter):
    def __init__(self, name=None, value=None, parameter=None, parent=None):
        if value and not isinstance(value, bool):
            raise ValueError(f'Parameter value [{value}] has to be bool()')

        self.parameters = self.set_parameters(parent)

        if parameter:
            self.parameter = parameter
        else:
            self.parameter = Parameter(self.parameters.CreateBoolean(name, value))
```
Not self.parameter must be declared as parameter, but self itself! Tomorrow I can deal more intensively with this problem :)

**Comment by evereux** [comment]
> I have to thank you. Because of your python library I was able to build up my master thesis successfully last year :) And it simply combines two very interesting areas: programming and CAD design!

That's great to hear. I'm glad this library was able help! 👍 


I've got the BoolParam class working as I expect it to now I think. I went back to the auto-generated one and rebuilt from there.

    class BoolParam(Parameter):

        def __init__(self, com_boolean_parameter):
            super().__init__(com_boolean_parameter)

        @property
        def value(self):
            return self.parameter.Value

        @value.setter
        def value(self, value):
            self.parameter.value = value

        def __repr__(self):
            return 'BoolParam()'

**Comment by evereux** [comment]
in parameter.py I don't understand what this does?

    @property
    def type(self):
        """
        Returns the last element of parlament
        | Example:
        | Parameter.Name = Part.Name\\GeometricalSet\\SubGeometricalSet\\Element\\Radius
        | Parameter.type = Radius
        | EngineNom = Engine.Nomenclature
        :return: str
        """
        if self.is_renamed():
            return self.parameter.name00
        else:
            return self.parameter.name.rsplit("\\")[-1]

**Comment by Luanee** [comment]
First of all, I'm sorry for the typos. This function is a leftover from earlier projects. I needed this information, for example to be able to structure all parameters of a sketch (in Radius, FirstLength, SecondLength... etc. pp).

**Comment by evereux** [comment]
Bah, don't worry about typos. :)

I'm not sure how helpful that is as a part of the pycatia module? I've just made an enormous number of changes/additions to the development branch and may drop this soon.

**Pull request merged**
