### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by ptm-tm**
adding instruction how to run py script directly from catia

### CODE REVIEW

**Comment by evereux** [comment]
Within git can you:

* create a new branch, giving that branch a name related to this pull request.
* make sure that branch is upto date / synced with this repository master / development.
* merge just the changes you've made related to this pull request to this branch.
* submit a pull request.

This makes checking out and reviewing changes a easier for me.

With regards to the changes themselves:
* make the python version same as that stipulate in the minimum requirement in the README file. Currently that is 3.9.
* Keep the formatting consistent with the other examples. There are currently a lot of unnecessary statements as it's quite clear what the line is doing. 
* use a more consistent / pythonic syntax. Take a look at https://peps.python.org/pep-0008/

**Comment by ptm-tm** [comment]
hm mb i dont understand... branch is documentation... this not a python. or i need push to development branch?

**Comment by ptm-tm** [comment]
so many mistakes,,, and press wrong button)

**Comment by evereux** [comment]
I'm closing this as the comments have not been implemented.

**Pull request closed without merging**
