### PR TITLE
Layer and annotation

### PR DESCRIPTION
**Pull request by Tian-Jionglu**
see issue #81

### CODE REVIEW

**Comment by Tian-Jionglu** [comment]
I'll fix this conflict this week.

**Comment by Tian-Jionglu** [comment]
Conflicts are resolved.

**Comment by evereux** [comment]
I have merged this with the development branch. Be sure to sync my additional changes back to your branch. There are a large number of little changes.

Cheers

**Comment by evereux** [comment]
I need to fix the circular import errors I've made. Leave this with me.

**Comment by evereux** [comment]
OK. That's done.

When resolving circular imports by doing `import this.that from there` within a class method you need to add also add at the top of the file

``` python
from typing import TYPE_CHECKING

if TYPING_CHECKING:
    import this.that from there
```

The reason I broke your circular import fixes is when I ran `mypy pycatia` over the module the type check threw up errors. When I fixed those errors and then ran the tests I realized I should have done the above. I forgot about that too. Oops.

**Comment by evereux** [comment]
Also, can you add some tests to the test suit for this package? They're quite important.

**Pull request closed without merging**
