### PR TITLE
fix parameters.py: resolved errors in .item() function, extend and improve parsing of parameters

### PR DESCRIPTION
**Pull request by mokrueger**
Proposed fix for https://github.com/evereux/pycatia/issues/197.

This uses a new way to obtain the com_class type to then map it to the correct parameter class.
This parsing is experimental but seems to work for most things.

Fallback is the previous parsing solution.

### CODE REVIEW

**Comment by evereux** [comment]
Can you resolve this merge conflict please?

**Comment by mokrueger** [comment]
Done! :) Should work now as expected

**Comment by mokrueger** [comment]
Perhaps you can also check if works for you as well, since I am using the slightly modified com interface

**Comment by evereux** [comment]
Thanks!

I tried it out earlier and it worked fine for me. 👍

**Pull request merged**
