### PR TITLE
add name propery

### PR DESCRIPTION
**Pull request by ptm-tm**
add property name to axis system

### CODE REVIEW

**Comment by ptm-tm** [comment]
this better?
sry im not programmer im just old engineer)))

**Comment by ptm-tm** [comment]
this need for next example)

**Comment by evereux** [comment]
Nearly nailed it. :-)

Are you sure you couldn't already do this? This line `class AxisSystem(AnyObject):` means the class `AxisSystem` inherits the features of the class [AnyObject](https://github.com/evereux/pycatia/blob/master/pycatia/system_interfaces/any_object.py). Check out lines 81-121. The work is already done for you.

From one non-programming older engineer to another, you're doing good. :wink:

**Comment by ptm-tm** [comment]
hmm I'm check it and this not actually.
I'm not use it properly

**Pull request closed without merging**
