### PR TITLE
Support for searching catmaterial in multiple CATEnv paths 

### PR DESCRIPTION
**Pull request by whatDdev**
## Issue:

pytest fails when executed on CATIA environment having multiple CATEnv paths for startup(error log below) - 

```
tests\create_source_material.py:12: in get_cat_material
    raise FileNotFoundError(f'Could not find {catpart_materials}.')
E   FileNotFoundError: Could not find C:\Progra~1\CATIA\R27\\win_b64\startup;%NLRootPath%\win_b64\startup;%VNRootPath%\win_b64\startup;%CAIRootPath%\CAI_V5-6R2017\win_b64\startup\materials\Catalog.CATMaterial.
```

## Solution:

As `get_cat_material()` assumes single path to locate catmaterial in startup path. 
Modifying this method and searching catmaterial file in all possible startup paths solves the problem. 

PS.: Utility of searching in multiple paths can be moved to any other part of pycatia, for time being I am focusing on fixing just this issue.!

### CODE REVIEW

**Comment by evereux** [comment]
Thanks for this. I didn't consider multiple values could be used in the environment files. Not something I've ever needed to do.

I don't think anything need to be done regarding this elsewhere? Could be wrong ... Maybe add a comment to the `SystemService.environ()` method.

Within git can you:

    create a new branch, giving that branch a name related to this pull request.
    make sure that branch is upto date / synced with this repository master / development.
    merge just the changes you've made related to this pull request to this branch.
    submit a pull request.

This potentially makes checking out and reviewing changes a easier for me. If you make further changes to your developement branch unrelated to this PR that can make things confusing / out of sync.

* What does the function name dfs stand for? Can you give it a more explicit name please?

* I'm not familiar with multiple paths set in environment files. I can see the delimiter is `;` but are spaces valid after the `;`? I ask because you don't strip any potential white space causing unnecessary breakages.. I can test this at some point.

* `dir` is a built in function. It's not good practice to over-ride these.

* `from pathlib import Path` is no longer used. Please use this library over doing things like `os.path.join()`, `os.path.isfile()` etc to be consistent with this project.

* maybe a good idea to implement a linter of some kind to prevent the last two issues.

**Comment by whatDdev** [comment]
Thanks for your reply. 
Environment files have multiple values if you define prerequisite to default CATEnv. 
You can create custom environment using CATIAENV utility - 
"<CATIAInstallationRoot>\win_b64\code\bin\CATIAENV.exe"

I will check if SystemService.environ() method required to be updated.
I will create new branch in this repository and create PR again.

My comments inline for your questions - 
What does the function name dfs stand for? Can you give it a more explicit name please?
- *DFS stands for "Depth-First Search." It is a commonly used algorithm to search file recursively in directory.*

I'm not familiar with multiple paths set in environment files. I can see the delimiter is ; but are spaces valid after the ;? I ask because you don't strip any potential white space causing unnecessary breakages.. I can test this at some point.
- *Yes, delimiter is ;. we don't need to worry about spaces here as its handled by `split(os.pathsep)`*

dir is a built in function. It's not good practice to over-ride these.
- *alright, I will change this to appropriate name.*

from pathlib import Path is no longer used. Please use this library over doing things like os.path.join(), os.path.isfile() etc to be consistent with this project.
- *I see I did not use any Path dep here. Looks like its already exists in your code - https://github.com/evereux/pycatia/blob/f727018799c5286b47162d496365e5c0dfc45bbd/tests/create_source_material.py#L1*

**Comment by evereux** [comment]
>>I'm not familiar with multiple paths set in environment files. I can see the delimiter is ; but are spaces valid after the ;? I ask because you don't strip any potential white space causing unnecessary breakages.. I can test this at some point.

> Yes, delimiter is ;. we don't need to worry about spaces here as its handled by split(os.pathsep)

Check out the extra space below. The spaces aren't handled by os.pathsep().

```python

>>> import os
>>> my_paths = "C:\this is my path\file.txt; C:\this is my path2\file.txt"
>>> my_paths.split(os.pathsep)
['C:\this is my path\x0cile.txt', ' C:\this is my path2\x0cile.txt']
>>>
```

But, if CATIA won't load the env file if it has that space the point was moot. I just checked and CATIA will start up with the space after the semi-colon there so you need to strip the whitespace?

**Comment by evereux** [comment]
>> from pathlib import Path is no longer used. Please use this library over doing things like os.path.join(), os.path.isfile() etc to be consistent with this project.

>    I see I did not use any Path dep here. Looks like its already exists in your code -

Yes, where it was used in the code. You removed that usage but didn't remove the import.

**Comment by evereux** [comment]
> I will check if SystemService.environ() method required to be updated.

The method itself does not not need to be updated. It behaves as expected and I don't want to change that. I meant some form of note informing users they should check for multiple paths which can be separated by a `;`.

**Comment by evereux** [comment]
I've implemented a different solution for this in the development branch.

I still added you as contributor since without your help I wouldn't have known about this.

**Pull request closed without merging**
