### PR TITLE
Added a parameter interface

### PR DESCRIPTION
**Pull request by Luanee**
...to add, change and remove parameters, parameter and parametersets of Parts and Products. A corresponding CATPart (CF_Part_3.CATPArt) and example file (example_12.py) were also created.

### CODE REVIEW

**Comment by evereux** [comment]
Thank you so much for your contribution!

Can I ask that you take a look at the file `v5automation-generated.7z` and in particular the files `parameter.py` and `parameters.py` in the folder `generated/interfaces/KnowledgeInterfaces`. These files contain the building blocks from which your files should be created.

Also, it would be great if we could set / create parameter names. It looks to me we can only read? (see product.py for example of setters on property).

I can't try out / test what you've done at the moment but is the new CATIA file you've added release 21? I can't accept anything later than that as I can't test it.

And finally! :) I'll need some tests adding. But, I can probably do that once I can add / rename parameters.

Thanks again.

**Comment by Luanee** [comment]
At first a little off-topic: How could you create Python files from the Catia V5 - Automation manual? That would have saved me some work :D I will look at these corresponding files and integrate them into my files.

Creating parameters and changing their names and values is no problem. The commands are located in `parameter.py`. But i will optimize it too.

Ah i forget that CATIA has a big problem with different versions, especially with the downward compatibility. I made the CATIA file in release 26. Attached is a PNG file that shows the structure of my catpart. So that when the time comes, you can rebuild it with your CATIA version.

Thank you for your feedback and your work so far :)

CF_Part_3

**Comment by evereux** [comment]
> At first a little off-topic: How could you create Python files from the Catia V5 - Automation manual? That would have saved me some work :D

Yeah, genuinely sorry about that. I'll add something about contributing to the README. Should have done that sooner ...

The Automation Manual is a .chm file which is basically a collection of HTML files. So, I extracted those and wrote a script using BeautifulSoup4 to parse the html data and create the python files. It's a real hack fest. Partly because of me and mostly because the html data is so poorly / inconsistently formed.

> Attached is a PNG file that shows the structure of my catpart.

Perfect. After writing my post I realised I should have asked for just that.


Cheers

**Comment by Luanee** [comment]
The last days were a bit busy, so the changes took a bit longer. 

It would probably be best if I initiate a new pull request to keep a better overview of the changes, right?

**Comment by evereux** [comment]
> The last days were a bit busy, so the changes took a bit longer.

No problem. 

> It would probably be best if I initiate a new pull request to keep a better overview of the changes, right?

To be honest I'm not sure of best practices here. I'm not familiar with this process at all. Do whatever you feel is best. One thing I would like is that the pull request related to the parameter implementation contain only changes for just that. For example: The changes you have made to product.py are not related to the subject of the pull request. That should be a seperate pull request I think.

**Pull request closed without merging**
