### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by ptm-tm**
add measure testing ( interia,mass,cog etc)

### CODE REVIEW

**Comment by ptm-tm** [comment]
make the python version same as that stipulate in the minimum requirement in the README file. Currently that is 3.9.
i can change but i cant test this ver. python

**Comment by ptm-tm** [comment]
"use a more consistent / pythonic syntax. Take a look at https://peps.python.org/pep-0008/"
or CAA V5 Automation Coding Rules

**Comment by evereux** [comment]
> "use a more consistent / pythonic syntax. Take a look at https://peps.python.org/pep-0008/" or CAA V5 Automation Coding Rules

The CAA V5 Automation Coding Rules are absolutely not relevant here when writing python code which this library predominantly uses (unless it's some VBA called within a Class method).

**Comment by evereux** [comment]
You've got yourself into a pickle here. Looks like you've merged my changes to developement to the master branch and then pushed all those changes in this pull request. 

A lot of those changes do not to go into the master branch until the next release (just how this project is).

You'll need to fix this.

I'll accept changes to the master branch if they are not related to the pycatia application itself, new examples being an example. Your new examples are here but you've pushed all my other changes too.

**Comment by ptm-tm** [comment]
lol im try chamge parrent of my branch) mb delete and create new?
to newbe if i want add new @property i need pull requrest in development branch?

**Comment by evereux** [comment]
> lol im try chamge parrent of my branch) mb delete and create new?

Unfortunately I can't advise on the best course of action specifically as my git knowledge isn't great (especially the pull requests and syncing other repos etc) and my attempt to explain would probably only confuse more.  Do you use a GUI like gitkraken, that does help visualize what is going on if you like that kind of thing.

**Comment by evereux** [comment]
> to newbe if i want add new https://github.com/Property i need pull requrest in development branch?

That is what should happen here, yes. 👍

**Comment by evereux** [comment]
I'm not sure what I can do to resolve these issues. There are a lot of changes here unrelated to the original pull request I suspect (33 changed files).

It might be worth starting from a clean up to date branch and resubmitting?

**Comment by ptm-tm** [comment]
ок))

**Pull request closed without merging**
