### PR TITLE
Create coords_relative_to_axis_system.py

### PR DESCRIPTION
**Pull request by Mithro86**
Useful script to get the coordinates of a point relative to an axis system.

### CODE REVIEW

**Comment by evereux** [comment]
Great stuff, thanks for this.

I'm not a fan of the use of `global` here. They're a little frowned upon and not used unless strictly necessary which I don't believe they are here. Lots of articles out there regarding the use of them. I would simply move that section of code to before your function definitions and remove the global assignments.

**Comment by Mithro86** [comment]
Corrected. Thanks for the input!

**Comment by evereux** [comment]
Awesome, thanks. I'll merge as soon as I can.

**Comment by evereux** [comment]
What is the `normalize_vector` function doing within the function coords_relative_to_axis? I ask since the results n_x, n_y and n_z aren't used.

**Comment by Mithro86** [comment]
> What is the `normalize_vector` function doing within the function `coords_relative_to_axis`? I ask since the results `n_x`, `n_y` and `n_z` aren't used.

Nice catch, I had made an error. I did a new pull request with the corrected one.

**Comment by evereux** [comment]
> > What is the `normalize_vector` function doing within the function `coords_relative_to_axis`? I ask since the results `n_x`, `n_y` and `n_z` aren't used.
> 
> Nice catch, I had made an error. I did a new pull request with the corrected one.

It was pycharms catch, not mine. :-)

**Pull request merged**
