### PR TITLE
Method `get_tolerances` requires vba

### PR DESCRIPTION
**Pull request by deloarts**
The `get_tolerances` method from the `drawing_dimension` module requires vba to return the parameters.
The function now returns a tuple, where the types match the param-types from the CATIA docs.

```python
def get_tolerances(self) -> Tuple[int, str, str, str, float, float, int]:
    vba_function_name = "get_tolerances"
    vba_code = """
    Public Function get_tolerances(drawing_dimension)
        Dim oValues(7)
        drawing_dimension.GetTolerances tol_type, tol_name, tol_up_s, tol_low_s, tol_up_d, tol_low_d, tol_display

        oValues(0) = tol_type
        oValues(1) = tol_name
        oValues(2) = tol_up_s
        oValues(3) = tol_low_s
        oValues(4) = tol_up_d
        oValues(5) = tol_low_d
        oValues(6) = tol_display

        get_tolerances = oValues
    End Function
    """
    value = self.application.system_service.evaluate(
        vba_code, 0, vba_function_name, [self.com_object]
    )
    return value[0], value[1], value[2], value[3], value[4], value[5], value[6]
```

Formatting is done because of the setup of my editor, hope it doesn't bother you.

### CODE REVIEW

**Comment by evereux** [comment]
Thanks!

**Comment by evereux** [comment]
This method doesn't require VBA. If a method is broken and there isn't already a commented out VBA function there is a good chance that VBA isn't required (at least I haven't come across that case yet).

I've submitted a patch if you would like to take a look.

**Comment by evereux** [comment]
For future reference `Tuple[...]` should be `tuple[...]`.

**Comment by deloarts** [comment]
Yep, you're right, didn't need vba, thanks for checking.
I saw that the function required the return values as args, and assumed it would therefor need vba, but I think vba is only needed for by-ref arrays, or am I wrong here?
Will be more careful from now on.

**Comment by evereux** [comment]
This particular PR can be closed. 

Further changes should be submitted via a different PR with a title related to the changes involved.

**Pull request closed without merging**
