### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by ptm-tm**
Add section for portable catia or catia without installation. its consider for fix some errors from this purpose: Sometimes the COM object isn't registered properly when CATIA is installed. If the above isn't working you may need to re-install.

### CODE REVIEW

**Comment by ptm-tm** [comment]
add some usefull tips for catia

**Comment by evereux** [comment]
Is portable CATIA something supported by Dassault?

**Comment by ptm-tm** [comment]
> Is portable CATIA something supported by Dassault?

any catia is portable. u can use any destination folder and copy it.
but u can carry about enviroment text file were stored all paths.
its use in large companies whre need to centralised store some catia file and settings
sry my eng is bad)

**Comment by ptm-tm** [comment]
and u can carry about lic server. but your server stored in catia settings, but catia settings is pointed in enviroment file.

**Comment by ptm-tm** [comment]
and i dont say that catia is not licensed. its work in any redaction. ever student edition

**Comment by ptm-tm** [comment]
its simple command for register catia as com/ole server like regsvr32

**Comment by evereux** [comment]
OK. I never considered using CATIA V5 like that before. Makes sense it should work if there aren't any folder based registry settings that could break things.

I'll see if can tweak the wording a little so it's a little more generic as the command you've provided is ultimately useful for situations I've encountered too.

**Pull request merged**
